// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnaLLg1mQmtYwVmGzkGa_K8u4cPtwbn3Y',
    appId: '1:661187103153:android:5a47b5911e7b7402c65590',
    messagingSenderId: '661187103153',
    projectId: 'udemy-flutter-65ae4',
    databaseURL: 'https://udemy-flutter-65ae4-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-flutter-65ae4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_hta0inKGKWAzQZtTB3ogoC9yrV4xjA',
    appId: '1:661187103153:ios:661ee4d08f90ab91c65590',
    messagingSenderId: '661187103153',
    projectId: 'udemy-flutter-65ae4',
    databaseURL: 'https://udemy-flutter-65ae4-default-rtdb.firebaseio.com',
    storageBucket: 'udemy-flutter-65ae4.appspot.com',
    androidClientId: '661187103153-lt22mjpvp0umbgd70pgri8a8gvlm637f.apps.googleusercontent.com',
    iosClientId: '661187103153-3fj5fn3mn4sr8clv3pfsl68bcs81gsf7.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled2',
  );
}
